# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install necessary Python dependencies
RUN pip install --no-cache-dir mcp[cli]>=1.3.0 httpx>=0.28.1 python-dotenv>=1.0.0

# Copy project files
COPY . .

# Ensure Python output is unbuffered (real-time logs)
ENV PYTHONUNBUFFERED=1

# Default command to run the MCP server
CMD ["python", "server.py"]
